// Generated by CoffeeScript 1.9.1
(function() {
  var makeGlobal;

  makeGlobal = function(library, includeFunctions) {
    var i, key, len, results, results1, value;
    if (includeFunctions == null) {
      includeFunctions = null;
    }
    if (includeFunctions) {
      results = [];
      for (i = 0, len = includeFunctions.length; i < len; i++) {
        key = includeFunctions[i];
        results.push(this[key] = library[key]);
      }
      return results;
    } else {
      results1 = [];
      for (key in library) {
        value = library[key];
        results1.push(this[key] = value);
      }
      return results1;
    }
  };

}).call(this);
